services:
  proxy:
    image: nginx:1.27
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
    depends_on:
      - web

  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.prod

  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres_prod:/var/lib/postgresql/data
      - ./postgres_init_prod.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1Qwerty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  