services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.dev

  database:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres_dev:/var/lib/postgresql/data
      - ./postgres_init_dev.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1Qwerty
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  